### ISSUE TITLE
Issue with Coordinates that has a 0 in the beginning

### ISSUE THREAD

**Issue by Nicolai-YT** [siggel/coordinatejoker#49]
There is an issue.
I have this formula: N48° 23.044+x

If I put 50 in the field for x than the result is not correct. Coordinate jokes's result is N48° 23.**940** but the right result should be N48° 23.**094**.

So there is an issue if the first number after the dot would be zero.
I hope this could be solved.

**Comment by siggel** [comment]
I cannot reproduce it as described. 23.044+50 would give correctly 73.044 (which is not a valid coordinate - I see another bug there, that I don't get a message about an invalid coordinate but just nothing happens if the one and only result is invalid). The problem here is that often geocaching formulas are not formulated precisely. The formula 23.044 + 50 literally is 73.044. Intended by the owner was 23.0(44+50). Even worse I often face the problem, that some write 23.x with x=50 and some mean 23.050, others mean 23.50 which equals 23.500 like 1.5$=1.50$. So I don't see a solution to this, as coordinate joker cannot guess what the owner intended :(

**Comment by siggel** [comment]
Nicolai-YT, please contact me via the email given in the app if you would like to discuss it further (or user siggel on geocaching.com). I did not find a way here on github for contacting you directly.
